login:
  authenticated:
    redirect_url: /node/2
    allow_destination: false
    weight: 0
  content_editor:
    redirect_url: /node/2
    allow_destination: false
    weight: 0
  administrator:
    redirect_url: /node/2
    allow_destination: false
    weight: 0
logout:
  authenticated:
    redirect_url: /node/2
    allow_destination: false
    weight: 0
  content_editor:
    redirect_url: /node/2
    allow_destination: false
    weight: 0
  administrator:
    redirect_url: /node/2
    allow_destination: false
    weight: 0
